export const INPUT_EXAMINEE_DETAILS = "ADD_USER_DETAILS";
export const SET_QUESTION_LENGTH = "SET_QUESTIONS_LENGTH";
export const STOP_TEST = "STOP_TEST";
export const NEXT_QUESTION = "NEXT_QUESTION";
export const UPDATE_SCORE = "UPDATE_SCORE";
export const INITIALIZE_FROM_SESSION = "INITIALIZE_FROM_SESSION";
export const SET_ERROR_FLAG = "SET_ERROR_FLAG";
